import type { PlanData } from "./PricingCard";

/**
 * Données des 5 plans First Immo
 * Chaque plan contient les infos de prix, features clés et style
 */
export const plansData: PlanData[] = [
  {
    name: "Starter",
    tagline: "Entrée découverte pour les très petits opérateurs et nouveaux entrants.",
    price: "600€",
    period: "/ an",
    setup: "Sans onboarding fee",
    accentColor: "#1E293B",
    badgeBg: "#F1F5F9",
    features: [
      { label: "1 projet actif", included: true },
      { label: "Page projet standard", included: true },
      { label: "5 médias max", included: true, detail: "Photos et rendus" },
      { label: "3 documents max", included: true },
      { label: "Formulaire lead basique", included: true },
      { label: "Dashboard leads simple", included: true },
      { label: "KYC light (email + ID)", included: true },
      { label: "Support email (SLA 72h)", included: true },
      { label: "Score Transparence public", included: false },
      { label: "Badge Vérifié", included: false },
      { label: "Scoring leads A/B/C", included: false },
    ],
    ctaLabel: "Commencer",
  },
  {
    name: "Publié",
    tagline: "Base structurée pour construire votre historique de transparence.",
    price: "1 500€",
    period: "/ an",
    setup: "Onboarding bundlé (inclus)",
    accentColor: "#2563EB",
    badgeBg: "#EFF6FF",
    features: [
      { label: "1 projet actif", included: true },
      { label: "Page projet complète", included: true },
      { label: "15 médias max + 1 vidéo", included: true },
      { label: "20 documents max", included: true, detail: "Catégorisation incluse" },
      { label: "Formulaire lead standard", included: true },
      { label: "Onboarding guidé 7 jours", included: true },
      { label: "KYC complet", included: true },
      { label: "Updates format imposé", included: true },
      { label: "2 utilisateurs", included: true },
      { label: "Support email (SLA 48h)", included: true },
      { label: "Badge Vérifié", included: false },
      { label: "Scoring leads A/B/C", included: false },
    ],
    ctaLabel: "Choisir Publié",
  },
  {
    name: "Vérifié",
    tagline: "L'offre principale. Badge Vérifié, leads qualifiés A/B/C et pipeline complet.",
    price: "4 200€",
    period: "/ an",
    setup: "+ 800€ onboarding one-shot",
    accentColor: "#1A6B3C",
    badgeBg: "#E8F5EE",
    recommended: true,
    features: [
      { label: "2 projets actifs", included: true },
      { label: "Médias & vidéos illimités", included: true },
      { label: "Badge Vérifié Plateforme", included: true, detail: "Selon Charte" },
      { label: "Score Transparence /100 public", included: true },
      { label: "Scoring leads A/B/C", included: true },
      { label: "Pipeline lead complet", included: true },
      { label: "Doc Vault illimité + Data-room", included: true },
      { label: "Relance auto leads + SLA", included: true },
      { label: "Trafic prioritaire / ranking", included: true },
      { label: "Export leads CSV", included: true },
      { label: "3 utilisateurs", included: true },
      { label: "Support prioritaire (SLA 24h)", included: true },
    ],
    ctaLabel: "Choisir Vérifié",
  },
  {
    name: "Premium",
    tagline: "Service managé — Pages, cadence et pilotage mensuel par First Immo.",
    price: "7 200€",
    period: "/ an",
    setup: "+ 2 500€ onboarding one-shot",
    accentColor: "#F97066",
    badgeBg: "#FFF1F0",
    features: [
      { label: "3 projets inclus", included: true },
      { label: "Mise en forme premium des pages", included: true, detail: "Copy + structure managée" },
      { label: "Tout le plan Vérifié inclus", included: true },
      { label: "Jusqu'à 8 updates accompagnées/mois", included: true },
      { label: "Coaching score + conformité", included: true },
      { label: "Spotlight newsletter (1/trimestre)", included: true },
      { label: "Point pilotage mensuel (visio)", included: true },
      { label: "Reporting mensuel avancé", included: true },
      { label: "Support dédié (SLA 12h)", included: true },
      { label: "Formation équipe commerciale", included: true, detail: "1 session incluse" },
    ],
    ctaLabel: "Choisir Premium",
  },
  {
    name: "Enterprise",
    tagline: "Groupes multi-projets, équipes avancées et intégrations sur mesure.",
    price: "Sur devis",
    period: "",
    setup: "Onboarding sur devis",
    accentColor: "#7C3AED",
    badgeBg: "#F3EEFF",
    features: [
      { label: "Projets illimités", included: true },
      { label: "Multi-équipes / multi-rôles", included: true },
      { label: "Workflow validation interne", included: true },
      { label: "API / Webhooks / CRM", included: true },
      { label: "Déploiement multi-pays", included: true },
      { label: "Dashboard exécutif consolidé", included: true },
      { label: "Référent de compte dédié", included: true },
      { label: "SLA contractuel sur mesure", included: true },
      { label: "SSO / authentification entreprise", included: true, detail: "Sur devis" },
      { label: "Utilisateurs illimités", included: true },
    ],
    ctaLabel: "Nous contacter",
  },
];
